print("Welcome grocery store")
inventory= ["Apples", "Bananas", "Dates", "Carrots"]
print(inventory)
print("An new order of eggs added")
inventory.append("Eggs")
print("Updated Inventory")
print(inventory)
print("the Bananas has been soldout")
inventory.remove("Bananas")
print("Updated Inventory")
print(inventory)
print("Arranging of inventory")
inventory.sort()
print("Updated Inventory")
print(inventory)